apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: jfrog-service
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
      - image: gcr.io/jfrog2021/demo-service:latest
        ports:
        - containerPort: 8080